@server = http://localhost:8000
@productId = 8
@userId = 1

### 유저정보조회
GET {{server}}/user/1

### 로그인
POST {{server}}/login
Content-Type: application/json ; charset=UTF-8

{
    "email":"abc@email.com",
    "password":"1234"
}

### 유저 추가하기
POST {{server}}/user/2
Content-Type: application/json ; charset=UTF-8

{
    "nickname": "Hongildong123456",
    "email": "Hongildong123456@example.com",
    "password": "Hongildong!!12",
    "gender": 1,  // 남자: 1, 여자: 0
    "age": 30,
    "money": 0,  // 초기값으로 설정
    "point": 0,  // 초기값으로 설정
    "profile_image": null,  // 아직 프로필 이미지 없음
    "depth1": "서울시",
    "depth2": "영등포구",
    "depth3": "문래동",
    "depth4": "청년취업사관학교",
    "isActive" : 1, // 활동 정지 여부
    "isAdmin" : 1 // 관리자
}

### 새상품 가격 받아오기
GET {{server}}/product/search/api

### 검색 버튼 클릭시
POST {{server}}/product/search
Content-Type: application/json ; charset=UTF-8

{
    "searchKeyword" : "노란 옷"
}

### 전체 상품 조회
GET {{server}}/product/list

### id로 상품 조회
GET {{server}}/product/read?productId={{productId}}&userId={{userId}}

### 상품 추가 
POST {{server}}/product/write
Content-Type: application/json ; charset=UTF-8

{
    "productName" : "노란 옷",
    "userId": 1,
    "price": 4000,
    "content": "노란 옷 팔아요",
    "categoryName1" : "여성패션",
    "categoryName2" : "의류",
    "categoryName3" : "상의"

}

### 특정 상품 변경
//UPDATE `Player` SET `team_id`=?,`updatedAt`=? WHERE `productId` = ?
PATCH {{server}}/product/update?productId={{productId}}
Content-Type: application/json ; charset=UTF-8

{
    "productName" : "빨간 옷",
    "userId": 1,
    "price": 4000,
    "content": "야옹이",
    "categoryName1" : "여성패션",
    "categoryName2" : "의류",
    "categoryName3" : "상의"

}

### 특정 상품 삭제
DELETE {{server}}/product/delete?productId={{productId}}

### 좋아요 추가, 삭제 
GET {{server}}/product/likes?productId={{productId}}

### 좋아요 클릭시
POST {{server}}/product/likes?productId={{productId}}&userId={{userId}}
Content-Type: application/json ; charset=UTF-8

{
    "userId": 1   
}

### 신고 클릭시
POST {{server}}/product/report?productId={{productId}}&userId={{userId}}
Content-Type: application/json ; charset=UTF-8

{
    "userId": 1   
}



